# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('vk_page', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страница Вконтакте')),
                ('balance', models.FloatField(default=100.0, verbose_name='Баланс')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
