# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.FloatField(default=1000.0, verbose_name='Рейтинг'),
        ),
    ]
