# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nowPlayers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
